### PR TITLE
Release Version for Outlook (as Add-in)

### PR DESCRIPTION
**Pull request by lorisobi**
Release Outlook Add-In for Denna
-----------------
Please program a version of Denna for Email Clients

PSD:
[DennaConc3.zip](https://github.com/MahStudio/Denna/files/2332672/DennaConc3.zip)

TIFF:
[TIF.zip](https://github.com/MahStudio/Denna/files/2332680/TIF.zip)

### CODE REVIEW

**Comment by Mohsens22** [comment]
@lorisobi We are not planning to add outlook plugin ATM (we don't have devs) 
But I'll refer this to our design team to take a look.
So this PR will sit here for a while

**Comment by rmclassic** [comment]
@Mohsens22 Can u add the todo export as file and email as a temp solution?

**Comment by Mohsens22** [comment]
@rmclassic Open a feature request issue please

**Comment by Mohsens22** [comment]
@rmclassic Also I'd you know any office Dev that can help us, refer me

**Comment by lorisobi** [comment]
@Mohsens22 Ok

**Comment by Mohsens22** [comment]
Hey, thanks for this issue.
I'm currently working on a set of Office plugins that runs in Word, Excel, Access, PP etc.
That project lives here:
https://github.com/MahStudio/DennaForMSOffice
I suggest you to post related stuff there.

**Pull request closed without merging**
